### ISSUE TITLE
Maven repo not working

### ISSUE THREAD

**Issue by Smart123s** [xXSchrandXx/SpigotPlugins#3]
## Summary
Trying to build [FastLogin](https://github.com/games647/FastLogin) for BungeeCord fails, because it can't get the dependency [BungeeCordAuthenticator](https://github.com/xXSchrandXx/SpigotPlugins/tree/master/BungeeCordAuthenticator) from your maven repo.
For more details, see https://github.com/games647/FastLogin/runs/2132145498#step:5:1404

### HTTP 409 Conflict:
- https://repo.opencollab.dev/maven-snapshots/de/xxschrandxx/bca/BungeeCordAuthenticator/0.0.2/BungeeCordAuthenticator-0.0.2.pom
- https://repo.nukkitx.com/maven-snapshots/de/xxschrandxx/bca/BungeeCordAuthenticator/0.0.2/BungeeCordAuthenticator-0.0.2.pom (basically this rediretcs you to the previous URL)

### Invalid certificate:
- https://maven.gamestrike.de/mvn/de/xxschrandxx/bca/BungeeCordAuthenticator/0.0.3-SNAPSHOT/BungeeCordAuthenticator-0.0.3-SNAPSHOT.pom (accepting the certificate result in 404 Not Found)

### Package does not exists
*Although this one could be caused by me doing something wrong.*
- https://maven.pkg.github.com/xXSchrandXx/*/de/xxschrandxx/bca/BungeeCordAuthenticator/0.0.2-SNAPSHOT/BungeeCordAuthenticator-0.0.2-SNAPSHOT.pom

## Logs
```
[ERROR] Failed to execute goal on project fastlogin.bungee: Could not resolve dependencies for project com.github.games647:fastlogin.bungee:jar:1.11-SNAPSHOT: Failed to collect dependencies at de.xxschrandxx.bca:BungeeCordAuthenticator:jar:0.0.3: Failed to read artifact descriptor for de.xxschrandxx.bca:BungeeCordAuthenticator:jar:0.0.3: Could not transfer artifact de.xxschrandxx.bca:BungeeCordAuthenticator:pom:0.0.3 from/to nukkitx-repo (https://repo.nukkitx.com/maven-snapshots/): Transfer failed for https://repo.nukkitx.com/maven-snapshots/de/xxschrandxx/bca/BungeeCordAuthenticator/0.0.3/BungeeCordAuthenticator-0.0.3.pom 409 Conflict -> [Help 1]
```

**Comment by xXSchrandXx** [comment]
Sorry, I forgot to enable the Subdomain after changing the hoster.
Now it should work again.
